### ISSUE TITLE
Value cannot be null error when getting the state for some databases

### ISSUE THREAD

**Issue by onordberg** [microsoft/delta-kusto#113]
I know we have to do some digging to find what entity in the database that causes this error. Do you have any tips based on the stack trace below? Any likely/typical problems? A way to identify from `.show database schema as json`? The two databases it fails on have quite a few entities. 

```delta-kusto 0.10.5.112
Session:  b3760637-d456-425f-b3b4-a825f915b990

Activating Client...
Client Activated
Newer clients available:  0.10.5.112
Loading parameters at '../_config/get-db-state.yaml'
1 jobs
Job 'download-state':

Exception encountered:  System.ArgumentNullException ; Value cannot be null. (Parameter 'Entity name can't be null or empty')
Stack trace:     at DeltaKustoLib.CommandModel.EntityName..ctor(String name)
   at DeltaKustoIntegration.Kusto.KustoManagementGateway.<>c.<DeltaKustoIntegration.Kusto.IKustoManagementGateway.ReverseEngineerDatabaseAsync>b__8_1(IDataReader r)
   at DeltaKustoIntegration.Kusto.KustoManagementGateway.Select[T](IDataReader reader, Func`2 projection)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 )
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 )
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 )
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 )
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 )
   at DeltaKustoIntegration.Kusto.KustoManagementGateway.DeltaKustoIntegration.Kusto.IKustoManagementGateway.ReverseEngineerDatabaseAsync(CancellationToken ct)
   at DeltaKustoIntegration.Database.KustoDatabaseProvider.DeltaKustoIntegration.Database.IDatabaseProvider.RetrieveDatabaseAsync(CancellationToken ct)
   at delta_kusto.DeltaOrchestration.RetrieveDatabaseAsync(IDatabaseProvider currentDbProvider, String db)
   at delta_kusto.DeltaOrchestration.ProcessJobAsync(MainParameterization parameters, IKustoManagementGatewayFactory kustoGatewayFactory, IFileGateway localFileGateway, String jobName, JobParameterization job)
   at delta_kusto.DeltaOrchestration.ComputeDeltaAsync(String parameterFilePath, IEnumerable`1 pathOverrides, String sessionId)
   at delta_kusto.Program.RunOptionsAsync(CommandLineOptions options, String sessionId)
   at delta_kusto.Program.<>c__DisplayClass2_0.<<Main>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at delta_kusto.Program.Main(String[] args)```

**Comment by vplauzon** [comment]
Do you still experience the issue?

**Comment by davfre** [comment]
I work with @onordberg and tested this on the relevant projects. Happy to report that this issue no longer occurs with delta-kusto 0.13.0.120!

**Comment by vplauzon** [comment]
Very happy to hear that :)
