### ISSUE TITLE
Error in parsing of functions that contain a `distinct` with assignment to at least two new column names

### ISSUE THREAD

**Issue by davfre** [microsoft/delta-kusto#117]
### Minimal reproducible:

```
  .create-or-alter function deltakustofail()
  {
      let T = datatable(colA:int, colB:string)
      [
      1, "A",
      2, "B",
      ];
      T | distinct newColA=colA, NewColB=colB
  }
```

### Error trace upon attempting to get the database state:

Error:  Issue in running job 'download-state'
  Error:  Issue parsing script
  Error:  .create-or-alter function with (skipvalidation = "true") deltakustofail() {
let T = datatable(colA:int, colB:string)
[
1, "A",
2, "B",
3, "C",
];
T | distinct newColA=colA, NewColB=colB
}
    **Exception encountered:  System.InvalidOperationException ; Function body was expected to be surrounded by curly brace but isn't:**   {
let T = datatable(colA:int, colB:string)
[
1, "A",
2, "B",
3, "C",
];
T | distinct newColA=colA, NewColB
    Stack trace:     at DeltaKustoLib.CommandModel.CreateFunctionCommand.TrimFunctionSchemaBody(String body)
   at DeltaKustoLib.CommandModel.CreateFunctionCommand.FromCode(SyntaxElement rootElement)
   at DeltaKustoLib.CommandModel.CommandBase.CreateCommand(String script, KustoCode code, Boolean ignoreUnknownCommands)
   at DeltaKustoLib.CommandModel.CommandBase.ParseAndCreateCommand(String script, Boolean ignoreUnknownCommands)
  Exception encountered:  DeltaKustoLib.DeltaException ; Issue parsing script
  Stack trace:     at DeltaKustoLib.CommandModel.CommandBase.ParseAndCreateCommand(String script, Boolean ignoreUnknownCommands)
   at DeltaKustoLib.CommandModel.CommandBase.<>c__DisplayClass0_0.<FromScript>b__0(String s)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 )
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 )
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 )
   at DeltaKustoLib.CommandModel.CommandBase.FromScript(String script, Boolean ignoreUnknownCommands)
   at DeltaKustoIntegration.Kusto.KustoManagementGateway.DeltaKustoIntegration.Kusto.IKustoManagementGateway.ReverseEngineerDatabaseAsync(CancellationToken ct)
   at DeltaKustoIntegration.Database.KustoDatabaseProvider.DeltaKustoIntegration.Database.IDatabaseProvider.RetrieveDatabaseAsync(CancellationToken ct)
   at delta_kusto.DeltaOrchestration.RetrieveDatabaseAsync(IDatabaseProvider currentDbProvider, String db)
   at delta_kusto.DeltaOrchestration.ProcessJobAsync(MainParameterization parameters, IKustoManagementGatewayFactory kustoGatewayFactory, IFileGateway localFileGateway, String jobName, JobParameterization job)
    Exception encountered:  System.InvalidOperationException ; Function body was expected to be surrounded by curly brace but isn't:   {
let T = datatable(colA:int, colB:string)
[
1, "A",
2, "B",
3, "C",
];
T | distinct newColA=colA, NewColB
    Stack trace:     at DeltaKustoLib.CommandModel.CreateFunctionCommand.TrimFunctionSchemaBody(String body)
   at DeltaKustoLib.CommandModel.CreateFunctionCommand.FromCode(SyntaxElement rootElement)
   at DeltaKustoLib.CommandModel.CommandBase.CreateCommand(String script, KustoCode code, Boolean ignoreUnknownCommands)
   at DeltaKustoLib.CommandModel.CommandBase.ParseAndCreateCommand(String script, Boolean ignoreUnknownCommands)

**Comment by davfre** [comment]
That resolves the issue. Thank you for the fix!
