### ISSUE TITLE
System.Text.Json.JsonReaderException ; Expected end of string, but instead reached end of data.

### ISSUE THREAD

**Issue by 784651** [microsoft/delta-kusto#131]
Firstly, thank you for updating delta-kusto! We are using release 0.12.2.119. We have trouble with our ingestion mappings. I have to delete my ingestion mappings before delta-kusto is able to run again my adx. The stack:

```
Compute Delta...
Exception encountered:  System.Text.Json.JsonException ; Expected end of string, but instead reached end of data. Path: $[0].Properties.Path | LineNumber: 0 | BytePositionInLine: 26.
Stack trace:     at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo, Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at DeltaKustoLib.KustoModel.MappingModel.MappingAsJsonEquals(QuotedText otherMappingAsJson)
   at DeltaKustoLib.DeltaHelper.GetUpdated[M,K](IEnumerable`1 currents, IEnumerable`1 targets, Func`2 keyExtractor)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at DeltaKustoLib.KustoModel.TableModel.ComputeDelta(TableModel targetModel)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1)
   at System.Linq.Enumerable.ConcatNIterator`1.LazyToArray()
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1)
   at DeltaKustoLib.KustoModel.DatabaseModel.ComputeDelta(DatabaseModel targetModel)
   at delta_kusto.DeltaOrchestration.ProcessJobAsync(MainParameterization parameters, IKustoManagementGatewayFactory kustoGatewayFactory, IFileGateway localFileGateway, String jobName, JobParameterization job)
   at delta_kusto.DeltaOrchestration.ComputeDeltaAsync(String parameterFilePath, IEnumerable`1 pathOverrides, Boolean noLogs, String sessionId)
   at delta_kusto.Program.RunOptionsAsync(CommandLineOptions options, String sessionId)
   at delta_kusto.Program.<>c__DisplayClass2_0.<<Main>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at delta_kusto.Program.Main(String[] args)
  Exception encountered:  System.Text.Json.JsonReaderException ; Expected end of string, but instead reached end of data. LineNumber: 0 | BytePositionInLine: 26.
  Stack trace:     at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object, ReadStack& , Utf8JsonReader&)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , TCollection& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
```

**Comment by 784651** [comment]
Sample data:

.create-or-alter table ['MYTABLENAME'] ingestion json mapping "MYTABLENAME_MAPPING" "[{\"column\":\"fields\",\"path\":\"$['fields']\",\"datatype\":\"\",\"transform\":\"\"},{\"column\":\"name\",\"path\":\"$['name']\",\"datatype\":\"\",\"transform\":\"\"},{\"column\":\"tags\",\"path\":\"$['tags']\",\"datatype\":\"\",\"transform\":\"\"},{\"column\":\"timestamp\",\"path\":\"$['timestamp']\",\"datatype\":\"\",\"transform\":\"\"}]"

**Comment by 784651** [comment]
Thanks! Will try again today/tomorrow. Just now seeing this message!

**Comment by 784651** [comment]
THANK YOU!!!
