### ISSUE TITLE
Missing 'Azure.Identity' dependency

### ISSUE THREAD

**Issue by cohenjo** [microsoft/delta-kusto#86]
Hi,
When running with MSI enabled I get the following error:
```
Exception encountered: System.IO.FileNotFoundException ; 
Could not load file or assembly 'Azure.Identity, Version=1.3.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'. 
The system cannot find the file specified.
```

Version: 0.8.0.98

log trace:
```
$ /bin/delta-kusto -p /tmp/job-2258241656.yaml



delta-kusto 0.8.0.98


Activating Client...
Client Activated
Newer clients available: 0.8.0.98
Loading parameters at '/tmp/job-2258241656.yaml'
1 jobs
Job 'push-db1937-to-prod':


Error: Issue in running job 'push-db1937-to-prod'
Error: Issue running Kusto script '.show database schema as csl script' on cluster 'https://mcasrs02euw1jony.westeurope.kusto.windows.net/' / database 'db1937'
Exception encountered: System.IO.FileNotFoundException ; Could not load file or assembly 'Azure.Identity, Version=1.3.0.0, Culture=neutral, PublicKeyToken=****'. The system cannot find the file specified.


Stack trace: at Kusto.Cloud.Platform.Aad.AadManagedIdentityTokenCredentialsProvider..ctor(String nameForTraces)
at Kusto.Cloud.Platform.Aad.AadManagedIdentityTokenCredentialsProvider.CreateProviderFromString(String mi)
at Kusto.Data.Security.HttpClientAuthenticatorFactory.CreateAuthenticator(KustoConnectionStringBuilder kcsb)
at Kusto.Data.Net.Client.RestClient2.MakeHttpRequestAsyncImpl(String address, String csl, String ns, String databaseName, Boolean streaming, ClientRequestProperties properties, ServiceModelTimeoutKind timeoutKind, String clientRequestId, Stream body, StreamProperties streamProperties)
at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
at Kusto.Data.Net.Client.RestClient2.MakeHttpRequestAsync(ActivityType activityType, String baseAddress, String relativeAddress, String clientRequestIdPrefix, String ns, String databaseName, String csl, String addr, Boolean streaming, ClientRequestProperties properties, ServiceModelTimeoutKind timeoutKind, StreamProperties streamProperties)
at Kusto.Data.Net.Client.RestClient2.ExecuteControlCommandAsync(String databaseName, String command, String addr, ClientRequestProperties properties)
at DeltaKustoIntegration.Kusto.KustoManagementGateway.<>c__DisplayClass10_0.<<ExecuteCommandAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
at DeltaKustoIntegration.Kusto.KustoManagementGateway.ExecuteCommandAsync(String commandScript, CancellationToken ct)
Exception encountered: DeltaKustoLib.DeltaException ; Issue running Kusto script '.show database schema as csl script' on cluster 'https://mcasrs02euw1jony.westeurope.kusto.windows.net/' / database 'db1937'
Stack trace: at DeltaKustoIntegration.Kusto.KustoManagementGateway.ExecuteCommandAsync(String commandScript, CancellationToken ct)
at DeltaKustoIntegration.Kusto.KustoManagementGateway.DeltaKustoIntegration.Kusto.IKustoManagementGateway.ReverseEngineerDatabaseAsync(CancellationToken ct)
at DeltaKustoIntegration.Database.KustoDatabaseProvider.DeltaKustoIntegration.Database.IDatabaseProvider.RetrieveDatabaseAsync(CancellationToken ct)
at delta_kusto.DeltaOrchestration.RetrieveDatabaseAsync(IDatabaseProvider currentDbProvider, String db)
at delta_kusto.DeltaOrchestration.ProcessJobAsync(MainParameterization parameters, IKustoManagementGatewayFactory kustoGatewayFactory, IFileGateway localFileGateway, String jobName, JobParameterization job)
Exception encountered: System.IO.FileNotFoundException ; Could not load file or assembly 'Azure.Identity, Version=1.3.0.0, Culture=neutral, PublicKeyToken=****'. The system cannot find the file specified.
```

**Comment by vplauzon** [comment]
Fixed in 0.8.1
